server:
  port: 9111

spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_jpa?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


